[package]
name = "monolog"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio-native-tls", "chrono"] }
tokio = { version = "1.42.0", features = ["macros"] }
